import type { Metadata } from "next";
import { requireAuth } from "../lib/getSession";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
    title: "Upload your sound effects",
    description: "Generated by create next app",
};

export default async function UploadLayout({ children }: { children: React.ReactNode }) {
    const session = await requireAuth();

    if (!session) {
        redirect('/login?redirection=upload&callbackUrl=/upload');
    }

    return (
        <>
            {children}
        </>)
}