import type { Metadata } from "next";
import UserHeader from "../../components/UserHeader";
import { redirect } from 'next/navigation';
import Tab from "./tab";
import { requireAuth } from "../../lib/getSession";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await requireAuth();

    if (!session) {
        redirect('/login')
    }


    return (
        <div>
            <UserHeader variant="private" />
            <Tab />
            <div className="mt-7 ">
                {children}
            </div>
        </div>
    );
}