import type { Metadata } from "next";
import Providers from "./providers";
import "./globals.css";
import { Nunito } from 'next/font/google'
import Navbar from "./components/Navbar";
import Modal_Root from "./components/modals/Modal_Root";
import FetchLoading from "./components/fetchLoading";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-nunito',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`dark ${nunito.className}`}>
      <body
        className={` antialiased bg-gray-100 text-gray-900 dark:bg-zinc-950 dark:text-white`}
      >
        <Providers>
          <Navbar />
          <Modal_Root />
          <FetchLoading />
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            theme="colored"
            draggable
            pauseOnHover
          />
          <div className="max-w-7xl m-auto px-5 sm:px-7 py-5 sm:py-7">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
