import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Trending Sound Effects",
  description: "Generated by create next app",
};

export default function trendingLayout({children}:{children: React.ReactNode}){
    return(
    <>
     {children}
    </>)
}