import type { Metadata } from "next";
import UserHeader from "../components/UserHeader";
import { authOptions } from "../lib/auth";
import { getServerSession } from "next-auth";
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const session = await getServerSession(authOptions);

    if (!session) {
        redirect('/login')
    }

    return (
        <div>
            <UserHeader />
            {children}
        </div>
    );
}