import { z } from "zod";

/* ---------------- STATS ---------------- */

export const CatStatsSchema = z.object({
  likes: z.number().min(0).default(0),
  views: z.number().min(0).default(0),
  downloads: z.number().min(0).default(0),
});

/* ---------------- USER ---------------- */

export const CategoryUserSchema = z.object({
  uid: z.string().min(1, "User UID is required"),
  name: z.string().min(1, "User name is required"),
});

/* ---------------- MAIN CATEGORY ---------------- */

export const CategorySchema = z.object({
  sb_id: z.string().optional(), // generated by backend

  name: z
    .string()
    .min(3, "Name must be at least 3 characters")
    .max(100, "Name must be under 100 characters")
    .trim(),

  slug: z
    .string()
    .min(3)
    .transform((val) => val.toLowerCase().trim()),

  thumb: z
    .string()
    .url("Invalid thumbnail URL")
    .nullable()
    .optional(),

  visibility: z.boolean().default(true),

  total_sfx: z.number().min(0).default(0),

  stats: CatStatsSchema.default({
    likes: 0,
    views: 0,
    downloads: 0,
  }),

  user: CategoryUserSchema,
});

export type CategoryInput = z.infer<typeof CategorySchema>;
